### ISSUE TITLE
Unregister node from RKE2 after agent deletion

### ISSUE THREAD

**Issue by zifeo** [remche/terraform-openstack-rke2#12]
Currently RKE2 keeps the agent as NotReady:
```
NAME                     STATUS     ROLES                       AGE   VERSION
rke-cluster-blue-001     Ready      <none>                      65m   v1.21.5+rke2r2
rke-cluster-green-001    NotReady   <none>                      65m   v1.21.5+rke2r2
```

**Comment by remche** [comment]
@zifeo I did not manage to reproduce this issue. Can you provide a sanitized configuration ?

> Is there a reason/use case to use a non volume server or node?

In my use case I only use ephemeral volume for VM w/o any problem.

**Comment by zifeo** [comment]
> @zifeo Nice, do not hesitate to contribute back ;)
> Would be very happy to find a clean autoscaling method !

Node deletion seems stable so far. I am happy to bring https://github.com/zifeo/terraform-openstack-rke2 over (merge all here), but the expose module interface is rather different. What is your point of view on this? This is why I chose to start from scratch originally.
