### ISSUE TITLE
Octavia usage

### ISSUE THREAD

**Issue by fmoctezuma** [remche/terraform-openstack-rke2#16]
Hello,
Is it possible to define ` use_octavia = true ` as defined on the original terraform-openstack-rke repo ?
https://github.com/remche/terraform-openstack-rke/blob/master/modules/rke/main.tf#L158-L160
I couldn't find anything related with LBAAS or Octavia on this repo.

Thanks
Francisco

**Comment by remche** [comment]
If you mean K8S [Openstack CCM](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md), RKE2 does not install it natively. RKE version was using in-tree cloud-provider which is deprecated now.
You can refer [CCM](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md) documentation and [examples/cinder-csi-plugin](https://github.com/remche/terraform-openstack-rke2/tree/master/examples/cinder-csi-plugin) to see how to deploy via manifest.

I do not have access to a Octavia enabled Openstack right now but I would be happy to accept an example which leverage it !
