### ISSUE TITLE
Local Exec does not use specified ssh key

### ISSUE THREAD

**Issue by nicolasjouveamue** [remche/terraform-openstack-rke2#18]
I'm testing the minimal example on OpenStack to deploy a minimal cluster on OpenStack.
The image I'm using is a CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64 and requires to log using "centos" user and to use sudo for most things.

When launching the setup I've got the following error:

│ Error: local-exec provisioner error
│
│   with module.controlplane.null_resource.write_kubeconfig[0],
│   on .terraform/modules/controlplane/kubernetes.tf line 15, in resource "null_resource" "write_kubeconfig":
│   15:   provisioner "local-exec" {
│
│ Error running command 'scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@*.*.*.*:/etc/rancher/rke2/rke2-remote.yaml rke2.yaml': exit status 1.      
│ Output: Warning: Permanently added '*.*.*.*' (ECDSA) to the list of known hosts.
│ Load key "/root/.ssh/id_rsa": invalid format

The script tries to load the private key from default location although I've specified a different location and that I'm  not using any ssh_agent.

I think the test in https://github.com/remche/terraform-openstack-rke2/blob/master/kubernetes.tf#L16 should be inverted...

Here is my file:

module "controlplane" {
  source           = "remche/rke2/openstack"
  cluster_name     = var.cluster_name
  dns_servers      = var.dns_servers
  write_kubeconfig = true
  # image_name       = "ubuntu-20.04-focal-x86_64"
  image_name       = "CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64"
  flavor_name      = "m4.medium"
  public_net_name  = "fips_pool1"
  ssh_key_file = "/data/id_rsa"
  boot_volume_size = 20
  boot_from_volume = true
  use_ssh_agent = false
  system_user = "centos"
}

**Comment by remche** [comment]
@nicolasjouveamue thanks for the report, will investigate and fix it asap.
