### ISSUE TITLE
Strange hardcoded IPS in cloud-init template

### ISSUE THREAD

**Issue by nicolasjouveamue** [remche/terraform-openstack-rke2#19]
Hello;

I've spotted some strange hardcoded ips and reference to github projects in the cloud-init template:
- https://github.com/remche/terraform-openstack-rke2/blob/master/modules/node/files/cloud-init.yml.tpl#L21
- https://github.com/remche/terraform-openstack-rke2/blob/master/modules/node/files/cloud-init.yml.tpl#L26
- https://github.com/remche/terraform-openstack-rke2/blob/master/modules/node/files/cloud-init.yml.tpl#L16
Is this intended ?

**Comment by remche** [comment]
>     * https://github.com/remche/terraform-openstack- -rke2/blob/master/modules/node/files/cloud-init.yml.tpl#L21
>     * https://github.com/remche/terraform-openstack-rke2/blob/master/modules/node/files/cloud-init.yml.tpl#L26

169.254.169.254 is the IP of the [Openstack Metadata Service](https://docs.openstack.org/nova/rocky/user/metadata-service.html)

>     * https://github.com/remche/terraform-openstack-rke2/blob/master/modules/node/files/cloud-init.yml.tpl#L16

This is the fallback method to install [jq](https://github.com/stedolan/jq) if the image does not provide it.

**Comment by nicolasjouveamue** [comment]
OK Thank you for the clarification 👍
