### ISSUE TITLE
Ability to use existing network

### ISSUE THREAD

**Issue by elitswarfvinge** [remche/terraform-openstack-rke2#29]
Hello,

I'm looking into using your terraform provider, however I'm actually looking for a way to use an existing network, complete with security groups and subnets. I can't really seem to find a way to do it without forking your setup.

Is this something you already can do, or something you have thought about adding?

**Comment by remche** [comment]
@elitswarfvinge thanks for you interest on this module !
You're right that it's not possible to specify existing network/security group for now. The primary goal of this module is to go from zero to a working RKE2 cluster.

I would be happy to add this possibility in the future. I'm very happy with any PR adding it, too ;)

**Comment by elitswarfvinge** [comment]
Just wanted to check if you had it. When I have the time I think I'll go ahead and do that PR to see, because so far it is working perfectly for pretty much all of my requirements :)
