### ISSUE TITLE
cloud-init.yml.tpl: operator precedence wrong on JQ installation magic.

### ISSUE THREAD

**Issue by klar42** [remche/terraform-openstack-rke2#51]
The construct
`    which jq 2>&1 > /dev/null || sudo curl -sfL $JQ_URL -o $JQ_BIN && sudo chmod +x $JQ_BIN`
should correctly be
`    which jq 2>&1 > /dev/null || { sudo curl -sfL $JQ_URL -o $JQ_BIN && sudo chmod +x $JQ_BIN ;  }`

If "jq" binary is available, "sudo chmod ..." is executed and fails.

**Comment by remche** [comment]
fixed by 14f712e
