### ISSUE TITLE
Support creation of separated bastion host

### ISSUE THREAD

**Issue by poikilotherm** [remche/terraform-openstack-rke2#58]
Hi there!

First: thank you very much for putting this module online and mainting it. Open Source is hard. :smiley_cat: 

In our environment, we would like to have a separated bastion host, as we want to add more services aside from RKE, like separation of concerns and don't want to have so many SSH servers exposed.

I am hacking on an addition to this project which would allow the creation of a distinct bastion node *before* the RKE servers are created (I couldn't think of a way to do this outside, as we  network information is not yet available before the server nodes are created.)

Would you like to see a PR and accept a contribution?

**Comment by remche** [comment]
Thanks for your kind words and interest for this module !

I'm always happy to accept contribution, with few rules in mind:
- it should respect the non-opinionnated/composable approach of the module ;
- it should not break things (prefer opt-in) ;
- it should come with proper documentation ;

Happy to see your future PR !
