### ISSUE TITLE
Support load balancers to expose API

### ISSUE THREAD

**Issue by poikilotherm** [remche/terraform-openstack-rke2#59]
In our environment, IPs are expensive and it's a lot of effort to get DNS RR going. Because of this, we would like to create a loadbalancer to expose the K8s API instead of assigning lots of floating IPs.

This is kind of related to #53, although we don't want to reuse sth, but let this module handle it.

(For HTTP/HTTPS, we will create a separate loadbalancer with an octavia controller to expose the actual services. This can happen _after_ setting up the RKE cluster, so doesn't need to be a part of this, as you show in your examples.)

Would you like to see a PR and accept a contribution for this? (I'm already aware that you emphasize on backward compat, so I will make sure of that if possible)

**Comment by zifeo** [comment]
@poikilotherm This is the reason I [forked](https://github.com/zifeo/terraform-openstack-rke2) this great project, you might be interested in the different approach taken.

**Comment by poikilotherm** [comment]
@zifeo thanks for the pointer! I'll check it out!

**Comment by remche** [comment]
@poikilotherm see my comment on #58 ;)

**Comment by slavikos** [comment]
Hi @powellchristoph,

> https://gist.github.com/powellchristoph/90f982de9ec3532c1d486cf323009325

I used your snippet to create a LB, but now I get a certificate error when trying to connect with kubectl via the FP that is associated with the LB. How did you overcome the issue ?

**Comment by powellchristoph** [comment]
> Hi @powellchristoph,
> 
> > https://gist.github.com/powellchristoph/90f982de9ec3532c1d486cf323009325
> 
> I used your snippet to create a LB, but now I get a certificate error when trying to connect with kubectl via the FP that is associated with the LB. How did you overcome the issue ?

Sorry, you will need to add your domain and the FIP to the `additional_sans` for when it creates the TLS cert.

```
  additional_san = distinct(flatten([
    var.additional_sans,
    local.default_cluster_fqdn,
    var.controlplane_lb_enabled ? [openstack_networking_floatingip_v2.controlplane_lb[0].address] : []
  ]))
  ```
