### ISSUE TITLE
ssh_keypair_name and ssh_key_file variable logical conflict when write_kubeconfig is set true ?

### ISSUE THREAD

**Issue by slavikos** [remche/terraform-openstack-rke2#62]
I'm very new to terraform and also this very module, but I believe there is "logic conflict" issue in  the `write_kubeconfig` resource in [`controlplane/kubernetes.tf`](https://github.com/remche/terraform-openstack-rke2/blob/fac2ee565b958425366588fdcf3f4d2fb3a274c2/kubernetes.tf#L7) which fails when trying to connect to the server node because it "silently" uses the `ssh_key_file` variable even if the `ssh_keypair_name` variable is set.

**Comment by remche** [comment]
@slavikos thanks for the feedback. Just to be sure, could you provide a minimal failing setup ?
