### ISSUE TITLE
Deploy additional config files

### ISSUE THREAD

**Issue by powellchristoph** [remche/terraform-openstack-rke2#67]
I would like to add support for additional config files and would like some input before I drop a PR.

Specifically my use case. I would like to add additional audit logging. 

* Edit the config.yaml to include:
`audit-policy-file: /etc/rancher/rke2/audit-policy.yaml`

* Create `audit-policy.yaml` in `/etc/rancher/rke2` folder.

Currently, we can easily at the rke2 config file entry, but there is no way to drop the audit file itself. Perhaps manage `additional_files` in the cloud-init file as the manifests are done?

**Comment by remche** [comment]
Thanks @powellchristoph for the proposition to add a more generic way to add files.
I'm open and happy to accept PR on this and imho it makes sense to use such a mechanism as  for manifests files. The only question is should we deprecate `manifests_path` ans `manifests_gzb4` to avoid redundancy ?
